Feat/#17/실시간 채팅 기능 구현
Leets-Official/Xcellent-BE pull request #18
Opened 2024-11-04 03:42 UTC by yechan-kim

## 1. 무슨 이유로 코드를 변경했나요?
실시간 채팅 비즈니스 로직을 구현했습니다.
<br>

## 2. 어떤 위험이나 장애를 발견했나요?
STOMP와 redis를 사용해서 구현하였으나, 프론트와의 연결 문제로 직접 테스트는 하지 못했습니다.
  대체로 post 메서드를 따로 구현하여 DB에 잘 들어오는지 테스트 했습니다.
<br>

## 3. 관련 스크린샷을 첨부해주세요.
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/a1fd526d-1ede-4bb5-9615-53f55889c7e5">

<br>

## 4. 완료 사항
- close #17
<br>

## 5. 추가 사항

2024-11-04 06:36 UTC, ehs208 requested changes
어려운 부분 구현하느라 고생하셨습니다! 소켓 통신 쪽은 아는 지식이 없어 리뷰를 남기기가 어렵네요...
그래도 궁금한 부분이나 논의할 부분, 수정할 부분 등등 적어봤습니다! 답변 남겨주시면 감사드리겠습니다.

2024-11-04 06:36 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/global/redis/RedisPublisher.java
이 부분 같은 경우는 메세지 기능에서 Pub/Sub 기능을 위한 부분이라 보여지는데, `global` 부분 보다는 `DM` 도메인에 파일을 위치시키는건 어떻게 생각하시나요? 혹은 이메일 인증 구현을 위한 `RedisService` 파일처럼 따로 `Global` 아래에 `DM` 이라는 폴더를 생성해 관리하는 것도 나쁘지 않다고 생각됩니다!

2024-11-04 06:36 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/global/redis/RedisSubscriber.java
`RedisPublisher` 파일과 같은 의견입니다.

2024-11-04 06:36 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/global/config/SecurityConfig.java
> +							"/swagger/**", "/index.html", "/api/auth/**", "/api/chat-room/**", "/dm").permitAll()
이 부분은 추후 DM 발송시 JWT 토큰을 확인 하는 로직을 추가한 후 지워주시면 될 것 같습니다

2024-11-04 06:36 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/dm/service/DMService.java
> +				redisTemplateMessage.setValueSerializer(new Jackson2JsonRedisSerializer<>(DM.class));
이 부분은 `RedisConfig` 파일에서
```java
public RedisTemplate<String, DMDto> redisTemplateMessage(RedisConnectionFactory connectionFactory) {
		RedisTemplate<String, DMDto> redisTemplateMessage = new RedisTemplate<>();
		redisTemplateMessage.setConnectionFactory(connectionFactory);
		redisTemplateMessage.setKeySerializer(new StringRedisSerializer());
		redisTemplateMessage.setValueSerializer(new Jackson2JsonRedisSerializer<>(String.class));
		return redisTemplateMessage;
	}
```
로 이미 사용되고 있는데 중복해서 사용하는 이유가 있을까요?

2024-11-04 06:36 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/dm/service/DMService.java
> +		redisTemplateMessage.setValueSerializer(new Jackson2JsonRedisSerializer<>(DM.class));
이 부분도 이미 `redisConfig` 에서 정의된 부분 같아보입니다!

2024-11-04 06:36 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/dm/domain/DM.java
> +		super();
혹시 여기에 `super`가 들어간 이유를 알 수 있을까요?

2024-11-04 06:36 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/chatRoom/service/ChatRoomService.java
> +		List<DMResponse> dmRespons = new ArrayList<>();
혹시 `dmRespons`라고 적으신건 단순 오타일까요 아니면 의도된 부분이실까요..? 😅

2024-11-04 06:36 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/chatRoom/controller/ChatRoomController.java
> +		User user = userRepository.findByEmail(email).orElseThrow(UserNotFoundException::new);
컨트롤러에서 레포지토리에 접근하는건 좋지 않다 생각합니다! 또한 저는 이 과정을 컨트롤러에서 `AuthenticationPrincipal`를 이용 하는 방법이 아닌, 서비스단에서 직접 JWT 토큰에 접근하여 인증하는 방법으로 구현했습니다만,, 어떤 방법이 더 좋은 방법인지는 모르겠습니다 🫠
또한 이 방법을 그대로 이용하신다면 중복되는 부분은 메소드로 추출해서 사용 할 수도 있을 것 같습니다!

2024-11-04 07:05 UTC, ehs208 requested changes

2024-11-04 07:05 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/chatRoom/controller/ChatRoomController.java
> +	@PostMapping()
URI가 비어있는데.. 의도 하신 부분인가요?

2024-11-05 16:07 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/redis/RedisPublisher.java
DM에서 관리하도록 수정했습니다!

2024-11-05 16:13 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/dm/service/DMService.java
> +				redisTemplateMessage.setValueSerializer(new Jackson2JsonRedisSerializer<>(DM.class));
삭제하는 것을 깜빡 했네요 삭제 하겠습니다!

2024-11-05 16:18 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/dm/domain/DM.java
> +		super();
오탈자 인것 같네요 수정하겠습니다!

2024-11-05 16:19 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/chatRoom/service/ChatRoomService.java
> +		List<DMResponse> dmRespons = new ArrayList<>();
단순 오타 입니다. 수정했습니다!

2024-11-05 16:33 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/chatRoom/controller/ChatRoomController.java
> +		User user = userRepository.findByEmail(email).orElseThrow(UserNotFoundException::new);
해당 부분은 서비스 로직으로 이관했습니다.

2024-11-05 16:38 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/chatRoom/controller/ChatRoomController.java
> +	@PostMapping()
해당 부분은 의도한 부분이 맞습니다.

`@RequestMapping("/api/chat-room")`으로 이미 해당 컨트롤러의 엔드 포인트가 `/api/chat-room`으로 시작되기 때문에 빈칸으로 놓게 된다면, 해당 API의 엔드 포인트는 `/api/chat-room`가 됩니다.
<img width="356" alt="image" src="https://github.com/user-attachments/assets/891f433e-ba49-434e-98bb-d21522bd2027">

하지만 이 부분이 의미가 잘 전달될지는 모르겠는데, 혹시 `create`라는 엔드 포인트를 추가하는 것에 대한 현수님의 의견이 궁금합니다!

2024-11-05 16:44 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/chatRoom/controller/ChatRoomController.java
> +	@PostMapping()
제가 놓친 부분 설명해주셔서 감사합니다!

`create` 라는 엔드포인트는, 사실 저도 URI를 작성하면서 평소에 `Restful 네이밍 컨벤션`을 크게 신경쓰지는 않지만,, 동사를 사용하는건 좋지 않다고 알고 있습니다.  
그래도 만약 예찬님 판단 하에 `create` 엔드포인트가 필요하시다면 추가하셔도 좋을 것 같습니다.

2024-11-05 16:53 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/chatRoom/controller/ChatRoomController.java
> +	@PostMapping()
저도 같은 생각이라 엔드 포인트는 변경하지 않겠습니다!

2024-11-05 17:07 UTC, ehs208 approved these changes

2024-11-06 06:08 UTC, merged

2024-11-07 06:36 UTC, dyk-im commented
리뷰가 늦었습니다... 실시간 채팅 기능 코드를 보니 상당히 어려워 보이는데 만드시느라 고생하셨습니다 !!!