[feat] 작성한 게시글미디어 조회 기능 구현
Leets-Official/Xcellent-BE pull request #19
Opened 2024-11-04 08:39 UTC by ehs208

## 1. 무슨 이유로 코드를 변경했나요?

작성한 게시글 조회 API 구현

<br>

## 2. 어떤 위험이나 장애를 발견했나요?

미디어 조회 기능의 경우 엔티티(ERD) 설계 부분에서 문제가 있다고 생각되어 회의 후 재구현할 예정입니다.

<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항
- 특정 사용자의 게시글 조회
<br>

## 5. 추가 사항
현재 게시글 작성 API가 없어 포스트맨으로 테스트가 불가능해, 직접 간단한 테스트코드를 작성해 작동을 확인하였으나 추후 수정이 필요할 수 있습니다.

2024-11-05 17:07 UTC, yechan-kim requested changes
고생하셨습니다! 궁금한 점이나 의견을 달아두었으니 확인 부탁드립니다!

2024-11-05 17:07 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/post/dto/ArticlesResponseDto.java
> +	}
static factory method 패턴의 네이밍에는 정해진건 없지만 통상적으로

- from : 파라미터 하나
- of : 파라미터 여러 개
- valueOf : from과 of의 더 자세한 버전

등등 이펙티브 자바 item1 (p12~13)에 정의되어 있으니 참고해 보면 좋을 것 같습니다!
물론 자신만의 기준이 있다면, 꼭 책의 내용을 따를 필요는 없다고 생각해요!
추가적으로 관련된 [링크](https://velog.io/@saint6839/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EB%84%A4%EC%9D%B4%EB%B0%8D-%EB%B0%A9%EC%8B%9D)를 남겨 둘 테니 한번 읽어보세요!

2024-11-05 17:07 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/post/service/PostService.java
> +
`Object[]`를 사용한 이유가 궁금합니다!

2024-11-05 17:07 UTC, yechan-kim commented on src/test/java/com/leets/xcellentbe/domain/post/service/PostServiceTest.java
테스트 코드를 통한 테스트 방법은 아주 좋은 것 같습니다!

2024-11-05 17:11 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/post/dto/ArticlesResponseDto.java
> +	}
감사합니다! 안그래도 최근 정적 팩토리 메소드 관련해서 공부해 볼 참이였는데 도움이 된 것 같습니다! `of`로 변경 했습니다!

2024-11-05 17:15 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/post/service/PostService.java
> +
`getPosts` 메소드를 가보시면, `PostRepository`의 `findPostsByWriter`에서 값을 반환 받고 있습니다.

```java
	@Query("SELECT p, pm.filePath FROM Post p LEFT JOIN PostMedia pm ON p.postId = pm.post.postId WHERE p.writer = :user")
	List<Object[]> findPostsByWriter(User user);
```

`Post`와 `PostMedia`를 조인해서, `filePath`를 가져오다보니,, 마땅히 사용할만한 제네릭 타입이 없어 우선 `Object`로 지정해 두었습니다.

혹시 더 좋은 의견 있으시면 적극 반영하도록 하겠습니다 😭

2024-11-06 05:31 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/post/service/PostService.java
> +
```
public record PostDto(
	Post post,
	String filePath
) {
}
```
이런식으로 따로 DTO를 생성해서

```suggestion
	@Query("SELECT new com.leets.xcellentbe.domain.post.dto.PostDto(p, pm.filePath) "
		+ "FROM Post p LEFT JOIN PostMedia pm ON p.postId = pm.post.postId " + "WHERE p.writer = :user")
	List<PostDto> findPostsByWriter(User user);
```
위와 같이 변경하시는 건 어떨까요?

2024-11-06 05:43 UTC, yechan-kim commented
추가적으로 프런트 분들이 `SWAGGER`를 통해 테스트가 가능하도록 `SecurityConfig`에 해당 API를 추가 부탁드리겠습니다!

2024-11-06 05:45 UTC, yechan-kim requested changes
추가적으로 프런트 분들이 `SWAGGER`를 통해 테스트가 가능하도록 `SecurityConfig`에 해당 API를 추가 부탁드리겠습니다!

2024-11-06 09:12 UTC, ehs208 commented
> 추가적으로 프런트 분들이 `SWAGGER`를 통해 테스트가 가능하도록 `SecurityConfig`에 해당 API를 추가 부탁드리겠습니다!

<img width="589" alt="image" src="https://github.com/user-attachments/assets/65aa185d-d839-4604-abeb-b5a409d7c29c">

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/bf5cdf56-dbf6-42e5-90a7-43e5fb6c0aba">


`SwaggerConfig` 및 `SecurityConfig` 설정 변경하여, `Swagger` 문서에서 헤더에 토큰을 추가할 수 있게 변경하였습니다..!

추가로.. 스웨거 문서를 보니 리스폰스에 문제가 있어 수정이 필요할 것 같습니다..😔

2024-11-06 16:18 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/post/service/PostService.java
> +
말씀하신 부분 반영하여 서비스 및 레포지토리 수정 하였습니다!

2024-11-07 05:28 UTC, yechan-kim approved these changes, later dismissed
고생하셨습니다!

2024-11-07 14:42 UTC, dyk-im approved these changes, later dismissed
코드 작성하시느라 고생하셨습니다! 큰 문제 없는 것 같습니다. 저랑 겹치는 부분은 편하게 수정하시면 될 듯 합니다! 리뷰가 좀 늦었습니다. 죄송합니다..!

2024-11-08 18:56 UTC, ehs208 commented
Conflict 모두 해결했습니다..
우선 제가 만든 API는 두가지 모두 잘 작동합니다...

2024-11-08 20:47 UTC, dyk-im approved these changes
컨플릭트 해결하느라 고생하셨습니다 ㅠㅠ

2024-11-09 16:34 UTC, merged