[feat] #1 CI/CD 구성
Leets-Official/Xcellent-BE pull request #2
Opened 2024-09-22 11:43 UTC by ehs208

## 1. 무슨 이유로 코드를 변경했나요?
Docker와 Github Actions을 통한 CI/CD 초기 세팅
<br>

## 2. 어떤 위험이나 장애를 발견했나요?

<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항

<br>

## 5. 추가 사항

2024-09-22 12:28 UTC, yechan-kim requested changes
고생하셨습니다! 코드를 읽어보고 궁금한 내용이나, 의견을 달아두었으니, 확인 부탁드립니다.
또한 몇몇 파일에 EOF 경고가 발생하는 지점이 많이 보이는데, IntelliJ에서 설정도 가능하니 한번 알아보시면 좋을 것 같습니다!

2024-09-22 12:28 UTC, yechan-kim commented on .github/workflows/github-actions.yml
> +          distribution: 'temurin'
프로젝트는 지금 JDK 17로 설정이 되어있는데, JDK 버전에 따라 다르게 사용되는 문법이 있기 때문에, 프로젝트와 GitHub Actions의 JDK 버전을 같이 사용해야 하는 걸로 알고 있습니다. 버전이 달라도 무방한 이유가 있을까요? 관련된 자료도 같이 첨부해 주시면 좋을 것 같습니다!

2024-09-22 12:28 UTC, yechan-kim commented on .github/workflows/github-actions.yml
> +        run: ./gradlew build -x test
빌드를 `test`로 빌드 하시는 이유가 있을까요?

2024-09-22 12:28 UTC, yechan-kim commented on .github/workflows/github-actions.yml
> +            sudo docker image prune -f
추후에 환경 변수가 확립이 된다면, 이 부분에 환경 변수를 넣어주면 될 것 같습니다!

2024-09-22 12:45 UTC, ehs208 commented on .github/workflows/github-actions.yml
> +          distribution: 'temurin'
관련 부분 수정해서 jdk 17로 바꾸어 두겠습니다.

2024-09-22 12:46 UTC, ehs208 commented on .github/workflows/github-actions.yml
> +        run: ./gradlew build -x test
test를 생략하고 빌드하는 부분으로 알고있는데, test는 로컬에서 이미 진행된 채로 머지가 될거라 생각하고 생략해놨습니다!

2024-09-22 12:52 UTC, ehs208 commented on .github/workflows/github-actions.yml
> +            sudo docker image prune -f
환경 변수라면 혹시 `secret.` 이부분 말씀이신가요? 이 부분은 깃허브 레포내에서 secret key로 지정해두어 정상작동 하는 부분입니다!

2024-09-22 15:36 UTC, yechan-kim commented on .github/workflows/github-actions.yml
> +            sudo docker image prune -f
```bash
sudo docker run -d --log-driver=syslog -p 8080:8080 \
            -e DB_USER=${{secrets.DB_USER}} \
            -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
            -e DB_URL=${{secrets.DB_URL}} \
            -e JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}} \
```
이런 식으로 `-e` 옵션을 통해서 `secret key`에 저장된 환경 변수를 Docker에 넘겨주면 좋을 것 같다는 의견이었습니다 :)

2024-09-23 01:37 UTC, yechan-kim commented on .github/workflows/github-actions.yml
> +            sudo docker image prune -f
확인해 보니, `application.yaml`을 `.gitignore`에 추가했기 때문에, 환경 변수를 사용하지 않아도 될 것 같아서 문제가 없을 것 같습니다! 고생하셨습니다!!!

2024-09-23 01:38 UTC, yechan-kim approved these changes

2024-09-23 01:46 UTC, merged