Feat/#16/게시글 작성게시글 삭제 기능 구현
Leets-Official/Xcellent-BE pull request #20
Opened 2024-11-06 07:02 UTC by dyk-im

## 1. 무슨 이유로 코드를 변경했나요?
게시글 작성과 관련된 (게시글(작성, 삭제, 조회)), 해시태그(작성, 삭제), 리포트스(작성, 삭제), 미디어(업로드, 삭제), 메인 페이지 커서 기반 페이지 조회 기능을 구현
<br>

## 2. 어떤 위험이나 장애를 발견했나요?
S3 버킷을 활용한 업로드를 제외하고 나머지 기능을 모두 api와 db를 비교하며 테스트를 진행했습니다.
<br>

## 3. 관련 스크린샷을 첨부해주세요.
<img width="1076" alt="스크린샷 2024-11-06 오전 4 44 18" src="https://github.com/user-attachments/assets/0b4aec50-a618-4913-85f5-7d369d608cc0">
<img width="865" alt="스크린샷 2024-11-06 오후 2 08 26" src="https://github.com/user-attachments/assets/537bcede-f7d3-4b3e-badb-3ca94dc56abf">
<img width="846" alt="스크린샷 2024-11-06 오후 2 52 41" src="https://github.com/user-attachments/assets/ced0fd2a-2853-4333-aa02-c36dea9f6e6b">
<img width="835" alt="스크린샷 2024-11-06 오후 3 33 26" src="https://github.com/user-attachments/assets/1b76c8dc-df7e-45b2-ae56-4110cd407427">

<br>

## 4. 완료 사항
게시글에 관련된 이미지, 해시태그, 리포스트, 조회 기능을 구현했습니다.
<br>

## 5. 추가 사항
게시글 수정은 유료 기능으로 제외했습니다.

2024-11-06 19:02 UTC, ehs208 requested changes
수고 많으셨습니다 !
한가지 의문점이 드는 부분이,, `ArticleMediaService` 부분이 필요한지 잘 모르겠습니다.

`articleMedia` 엔티티는, article을 작성할 때, 사용자가 이미지 혹은 영상을 첨부할때 미디어 정보를 담아두는 엔티티라고 생각됩니다.

이때문에 미디어 생성, 조회, 삭제는 모두 직접 진행하는 것이 아닌 `article` 엔티티를 통해 진행되어야 할 것 같습니다.
아마 미디어를 직접 삭제하려고 한다면 `article_id`와 `FK`가 걸려있어 삭제가 되지 않을 것으로 예상됩니다.

결론은, 미디어 생성, 조회, 삭제 모두 `article` 엔티티와 서비스에서 담당하는게 맞다고 생각되는데, 혹시 어떻게 생각하시나요?

2024-11-06 19:02 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/article/controller/ArticleController.java
전반적으로, URI에 `create`, `delete` 등이 사용되었는데 가능하면 변경해 주는 것이 좋을 것 같습니다!
또, 같은 URI라도 다른 HTTP 메소드를 사용하는 경우 URI가 중복해도 문제가 없으니, 아예 지워주시는 것도 좋은 방법일 것 같습니다.

2024-11-06 19:02 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/article/dto/ArticleCreateResponseDto.java
> +	private String message;
메세지는 굳이 담지 않아도 괜찮을 것 같습니다!

2024-11-06 19:02 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/articleMedia/service/S3UploadMediaService.java
이 파일의 내용은 중복되는 부분이 많아 `global` 에 작성한 후, 추후 각 서비스에서 메소드를 호출 하는게 적절하다 생각합니다 🤔

`User` 도메인에서도 사용되는 부분이라 추후에 저랑 논의 후에 수정하는 것이 좋을 것 같습니다.

2024-11-06 19:02 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/article/controller/ArticleController.java
> +		@RequestBody ArticleRequestDto articleRequestDto){
`@RequestBody`가 아닌 `PathVariable`이나 `QueryString`으로 받아오는 것이 더 적절할 것 같습니다..!

2024-11-07 01:28 UTC, dyk-im commented
리뷰 감사합니다. 제가 api 테스트하며 수정한 부분들이 있는데 로컬에만 커밋되고 푸쉬가 제대로 되지 않은 것 같아 다시 반영하고 검토 사항 변경해서 수정 진행하겠습니다!

2024-11-07 02:58 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/article/dto/ArticleCreateResponseDto.java
> +	private String message;
메세지 부분 제거해서 생성된 게시글의 id만 반환되도록 변경했습니다!

2024-11-07 02:58 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/article/controller/ArticleController.java
> +		@RequestBody ArticleRequestDto articleRequestDto){
id만 필요한 부분들은 dto 대신 PathVariable을 받아올 수있도록 수정했습니다!

2024-11-07 02:58 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/article/controller/ArticleController.java
create와 delete 모두 제거했습니다. repost의 경우는 기능은 비슷하지만 겹칠것 같아 생성은 /repost, 제거는 /unRepost 로 두었습니다. 이 부분도 수정이 필요하다면 바꾸겠습니다!

2024-11-07 02:58 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/articleMedia/service/S3UploadMediaService.java
넵! 그렇게 하는게 중복 방지도 되고 더 좋은 것 같습니다!

2024-11-07 02:58 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/article/dto/ArticleCreateResponseDto.java
> +	private String message;
도메인이 분리되어 있어서 미디어 로직을 따로 둔 것이긴 하나 합치는 것이 오히려 맞겠다는 생각도 듭니다.
그리고 위에 리뷰 남겨주신대로 미디어 서비스의 경우 article 객체에서 생성할 때 경로를 받아와서 저장하도록 해뒀기에 합쳐서 문제될 부분은 없는 것 같습니다! 
조회 또한 따로 경로를 찾아야하는 것이 아니라면 필요없다고 생각되어 제거했습니다. 삭제위치를 article로 옮겨보겠습니다!

2024-11-07 03:27 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/article/dto/ArticleCreateResponseDto.java
> +	private String message;
S3 관련 부분은 추후 진행을 위해 현상 유지했고, 기존 미디어 서비스 부분은 게시글서비스 에서 처리하도록 합쳤습니다. 그리고 미디어 경로도 제거시 삭제 상태를 저장하도록 엔티티에 필드 추가했습니다!

2024-11-07 05:51 UTC, yechan-kim reviewed
고생하셨습니다! 간단한 의견 남겨두었으니 읽고 의견 주세요!

2024-11-07 05:51 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/article/service/ArticleService.java
> +		}
저의 개인적인 생각으로는 게시글을 조회할 때, 내 게시글인지 확인하고, 그 결과를 `boolean`으로 프런트에 보내주면 프런트에서는 그 결과에 따라 수정 및 삭제 버튼을 보이게 하면, 삭제에 접근하기 힘들 것 같은데, 해당 로직을 추가하는 것에 대한 동윤 님의 의견이 궁금합니다!

2024-11-07 06:33 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/article/service/ArticleService.java
> +		}
유저 검증 로직이 게시글을 삭제할 때 오류를 미연에 방지하고자 만든 것인데 불 값을 전달해서 검증하고 효율적으로 처리하는 방식으로 바꾸는 것도 괜찮은 것 같습니다! 그러면 처리 과정에서 dto에 검증 값을 보내도록 해보면 어떨까요?

2024-11-07 06:46 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/article/service/ArticleService.java
> +		}
네 그렇게 하면 프런트에서 처리하기 쉬울 것이라고 생각합니다!

2024-11-07 08:26 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/article/service/ArticleService.java
> +		}
게시물 조회에서 본인 확인하는 로직 추가해서 본인 게시물지 확인하고 그 결과 값을 불 값으로 dto에 포함하여 전송하도록 변경했습니다!

2024-11-07 09:53 UTC, ehs208 approved these changes

2024-11-07 09:55 UTC, yechan-kim approved these changes

2024-11-07 10:08 UTC, merged