[feat] 게시글 좋아요 / 게시글 댓글 기능 구현
Leets-Official/Xcellent-BE pull request #23
Opened 2024-11-10 17:47 UTC by dyk-im

## 1. 무슨 이유로 코드를 변경했나요?
게시글 좋아요, 댓글 좋아요, 댓글 작성 (대댓글 작성 포함), 뷰, 좋아요, 리포스트, 코멘트 카운트 기능, 게시글 + 댓글 전체 조회 기능을 추가하기 위해 코드를 변경했습니다.
<br>

## 2. 어떤 위험이나 장애를 발견했나요?
오류 및 에러는 코드와 api 테스트를 통해 해결했습니다.
<br>

## 3. 관련 스크린샷을 첨부해주세요.
<img width="618" alt="스크린샷 2024-11-11 오전 1 37 16" src="https://github.com/user-attachments/assets/cf2c81a4-4b60-4a3c-b0d2-42fe38fba2a9">
<img width="611" alt="스크린샷 2024-11-11 오전 1 47 00" src="https://github.com/user-attachments/assets/a46efd58-a32f-4af9-92aa-3b1595ba217d">
<img width="738" alt="스크린샷 2024-11-11 오전 1 56 48" src="https://github.com/user-attachments/assets/cb327861-d0f1-405d-9f41-6bba79f8f091">
<img width="729" alt="스크린샷 2024-11-11 오전 2 27 19" src="https://github.com/user-attachments/assets/33cb0d87-c5b9-4c52-b957-cbc7195938eb">

<br>

## 4. 완료 사항
게시글 + 댓글 전체 조회, 게시글 좋아요, 댓글 좋아요, 댓글 작성 (대댓글 작성 포함), (뷰, 좋아요, 리포스트, 코멘트) 카운트 기능을 추가 구현 완료했습니다.
<br>

## 5. 추가 사항
추가적으로 중복으로 불러오거나 불필요한 코디 제거 진행했습니다. (댓글을 통해 이미지와 해시태그는 추가할 수 없고 댓글의 댓글의 댓글의 댓글 같은 형태는 불가능합니다.)

2024-11-11 02:05 UTC, ehs208 requested changes
고생하셨습니다! 현재 마감까지 얼마 남지 않은 관계로 우선 바로 눈에 보이는 부분들만.. 수정 요청 드렸습니다..

2024-11-11 02:05 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/article/domain/Article.java
>  	private int viewCnt, repostCnt, likeCnt, commentCnt;
엔티티 파일에 변수를 이러한 방식으로 추가해주시면, DB의 테이블에 해당하는 열들이 생성되게 됩니다.
의도하신 부분이 아니라면 수정해주시면 좋을 것 같습니다.

2024-11-11 02:05 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/comment/domain/Comment.java
> +	private int viewCnt, likeCnt, commentCnt;
이 부분도 마찬가지입니다.

2024-11-11 02:05 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/commentLike/dto/CommentLikeResponseDto.java
> +	private Long userId;
사용자에게 userId 보다는 다른 정보를 노출시키는게 좋을 것 같습니다.

2024-11-11 02:29 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/commentLike/dto/CommentLikeResponseDto.java
> +	private Long userId;
writerId를 보내는 부분과 혼동이 있었던 것 같네요... 해당 CommentLikeResponseDto에서 userId 부분 제거하면서 ArticleLikeResponseDto 에도 있는 userId 파트 함께 제거했습니다!

2024-11-11 02:45 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/article/domain/Article.java
>  	private int viewCnt, repostCnt, likeCnt, commentCnt;
일단 private int viewCnt, repostCnt, likeCnt, commentCnt;부터 설명드겠습니다. x의 게시물에는 뷰, 리포스트, 좋아요, 댓글 수를 카운트하는 기능이 필요하고, 각 객체마다 지니는 데이터라고 생각해서 추가했습니다. 조회성능에 중점을 두면 이 방식이 좋아보이고, 동시성을 생각하면 쿼리로 찾는 기능이 좋아보이는데 현수님은 어떻게 생각하시나요? (아래 코멘트도 동일한 의견입니다!)

2024-11-11 02:53 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/comment/domain/Comment.java
> +	private int viewCnt, likeCnt, commentCnt;
일단 위의 게시글도 그렇고 댓글도 그렇고 현재 @OneToMany(mappedBy = "parentComment") 이 어노테이션을 사용한 부분의 경우 양방향 매핑을 위해 관계를 정의한 부분으로 DB테이블에 열이 따로 생기지 않는 걸로 알고있습니다(데이터 그립으로도 확인 했는데 생성된 열은 없었습니다!) => 저렇게 정의를 해두면 연결된 테이블에 외래키가 생기고 해당 외래키를 통해 참조 관계가 관리됩니다. => JPA에서 해당 정의를 통해 자동으로 comment와 article을 매핑해주고 comment가 요청될 때 해당 리스트가 지연로딩 됩니다. 
그렇기에 게시글을 사용하며 해당 데이터를 참조하기위해 작성한 코드입니다! 만약 제가 간과한 부분이 있거나 필요없는 코드라면 수정하겠습니다!

2024-11-11 03:00 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/comment/domain/Comment.java
> +	private int viewCnt, likeCnt, commentCnt;
혹시 몰라서 추가 링크와 https://velog.io/@dhk22/JPA-%EC%96%91%EB%B0%A9%ED%96%A5-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84
아래는 찾아본 내용과 비슷해서 Gpt 답변 첨부했습니다! 혹시 제가 잘못된 정보를 알고있다고 생각되시면 꼭 말해주세요 ㅠㅠ...
위와 같은 양방향 매핑은 엔티티 간의 관계를 설정한 것이고, 실제 테이블에는 외래 키(Foreign Key)로 나타나지만, 각 @OneToMany 필드가 독립적인 테이블로 생성되지는 않습니다.

자세히 설명하자면:
관계 설정: @OneToMany(mappedBy = "article")는 Hashtag, ArticleMedia, Comment가 Article을 참조하고 있다는 것을 나타내며, 각 테이블(hashtag, article_media, comment)에는 article_id라는 외래 키가 생깁니다.
실제 테이블 구조: 각 엔티티에 대해 독립적인 테이블이 생성되며, 연결 테이블은 따로 생기지 않고, 외래 키를 사용하여 참조 관계가 관리됩니다.
article 테이블에는 hashtags, mediaList, comments 리스트가 직접적으로 컬럼으로 추가되지 않습니다.
대신 hashtag, article_media, comment 테이블 각각에 article_id 컬럼이 추가되어 article과의 관계를 표현합니다.

양방향 매핑의 효과:
양방향 매핑을 통해 Article 엔티티를 통해 hashtags, mediaList, comments에 접근할 수 있으며, 반대로 Hashtag, ArticleMedia, Comment에서도 Article에 접근할 수 있습니다.
이는 객체 간의 관계에서만 이루어지며, 데이터베이스에 리스트 필드가 저장되거나 나타나는 것은 아닙니다.
따라서, 실제 데이터베이스에 저장될 때는 관계가 외래 키를 통해 관리되며, Article 엔티티의 hashtags, mediaList, comments는 테이블의 컬럼으로 보이지 않습니다.

2024-11-11 07:32 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/comment/domain/Comment.java
> +	private int viewCnt, likeCnt, commentCnt;
엇 뭔가 착오가 있었던 것 같습니다 !!

```java
private int viewCnt, likeCnt, commentCnt;
```
저는 이 부분 말씀 드린 거였습니다 !! ㅎㅎ

2024-11-11 07:43 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/article/domain/Article.java
>  	private int viewCnt, repostCnt, likeCnt, commentCnt;
viewCnt를 제외한 나머지 값들은 쿼리로 처리하는게 좋을 것 같습니다!!
예를들어 `commentCnt`의 경우엔, 만약 사용자가 댓글을 추가할시 

1. 사용자가 댓글 작성
2. 댓글 정보 추가 
3. commnetCnt 컬럼 업데이트 
4. commentCnt 조회` 

가 반복적으로 수행되지만, 

만약 쿼리를 통해 조회 할 시 
1. 댓글 작성 
2. 댓글 정보 추가 
3. 쿼리문(count)로 개수 조회

로직으로 더욱 간결해지고 말씀 해주신 동시성까지 확보하고 있어 제가 말한 방법이 더 좋을거 같다 생각하는데, 어떻게 생각하시나요?

2024-11-11 07:45 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/comment/domain/Comment.java
> +	private int viewCnt, likeCnt, commentCnt;
앗... 착오가 있었네요 ㅎㅎ 윗 부분은 문제가 없다면 다행입니다!

아래에 카운트 관련 필드는 디비에 저장하고 가져오면 어떨까 하는 생각으로 만들었습니다.
조회수는 엔티티의 필드로 만들지 않을 경우 다르게 조회할 방도는 없다고 생각되고, 나머지 좋아요 수나 리포스트 수, 카운트 수는 쿼리로 찾아 ResponseDto에 담아서 전달할 수 있을 듯 합니다. 
의도는 맞으나 혹시 지금과는 다르게 쿼리의 COUNT를 통해 찾아오는 방식이 더 효율적이라고 생각하시나요???

2024-11-11 07:52 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/comment/domain/Comment.java
> +	private int viewCnt, likeCnt, commentCnt;
위에 리뷰 주신걸 답변으로 하겠습니다!

2024-11-11 07:56 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/article/domain/Article.java
>  	private int viewCnt, repostCnt, likeCnt, commentCnt;
저도 그 부분에 있어 고민이 있었는데 동시성 확보를 위해 수정하는 쪽이 좋을 것 같습니다! 수정 진행하겠습니다!

2024-11-11 12:43 UTC, ehs208 submitted a review, later dismissed

2024-11-12 02:00 UTC, ehs208 approved these changes

2024-11-12 02:09 UTC, merged