[feat] #2 도메인 생성
Leets-Official/Xcellent-BE pull request #4
Opened 2024-09-28 16:22 UTC by yechan-kim

## 1. 무슨 이유로 코드를 변경했나요?
1. 사전에 작성한 ERD를 기반으로 도메인을 생성했습니다.
2. `ISSUE_TEMPLATE`에 있는 오타를 수정하였습니다.
<br>

## 2. 어떤 위험이나 장애를 발견했나요?
1. join을 할 때 동일한 열이름을 사용하면 중복 참조 문제가 발생하는 장애가 발생하였습니다.
2. 외래 키 제약 조건에따라,  hashtag_id와 post_id 열이 호환되지 않는 장애가 발생하였습니다.
<br>

## 3. 관련 스크린샷을 첨부해주세요.
스크린샷 대신, 에러코드를 첨부하겠습니다.
1.
```bash
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in 
class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: [PersistenceUnit: 
default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Column 'user_id' is 
duplicated in mapping for entity 'com.leets.xcellentbe.domain.follow.domain.Follow' (use '@Column(insertable=false, 
updatable=false)' when mapping multiple properties to the same column)
```

2. 
```bash
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "alter table hashtag add constraint
 FKti88jlst42xs2jlof5d6p1t7c foreign key (hashtag_id) references post (post_id)" via JDBC [(conn=172) Referencing column 
 'hashtag_id' and referenced column 'post_id' in foreign key constraint 'FKti88jlst42xs2jlof5d6p1t7c' are incompatible.]
```
<br>

## 4. 완료 사항
- [x] 도메인 생성  
<br>

## 5. 추가 사항
- cloae #3

2024-09-28 17:10 UTC, ehs208 requested changes
고생하셨습니다! 혹시 몇가지 도메인 폴더에는 컨트롤러나 서비스 레포지토리 등 보일러 플레이트 코드가 누락된 부분이 보이는데 혹시 이유를 알 수 있을까요? 🫠

2024-09-28 17:10 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/comment/domain/Comment.java
> +	private User writer;
```suggestion
	@NotNull
	@ManyToOne(fetch = FetchType.LAZY)
        @JoinColumn(name = "writer_id")
	private User writer;
```

특별히 들여쓰기 한 이유가 없으시면 줄 맞춰주시면 좋을 것 같습니다! 😀

2024-09-28 17:10 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/comment/domain/Comment.java
> +	private Post post;
```suggestion
	@NotNull
	@ManyToOne(fetch = FetchType.LAZY)
        @JoinColumn(name = "post_id")
	private Post post;
```

여기도 들여쓰기 맞춰주시면 좋을 것 같습니다!

2024-09-28 17:23 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/comment/domain/Comment.java
> +	private User writer;
IDE 상으로는 들여 쓰기가 동일하게 되어있어서 놓쳤네요 감사합니다!

2024-09-28 17:25 UTC, yechan-kim commented
@ehs208
> 고생하셨습니다! 혹시 몇가지 도메인 폴더에는 컨트롤러나 서비스 레포지토리 등 보일러 플레이트 코드가 누락된 부분이 보이는데 혹시 이유를 알 수 있을까요? 🫠

서비스 레포지토리는 아직 서비스가 없기 때문에 따로 생성하지 않았고, 컨트롤러가 필요 없다고 판단된 도메인에는 컨트롤러를 생성하지 않았습니다. 혹시 컨트롤러가 필요한 부분이 있을까요? 제가 만들지 않은 부분은 해당 객체를 생성하는 책임이 다른 부분에 있다고 판단하고 있는데, 알려주시면 감사하겠습니다!

2024-09-28 18:11 UTC, ehs208 commented
> @ehs208
> 
> > 고생하셨습니다! 혹시 몇가지 도메인 폴더에는 컨트롤러나 서비스 레포지토리 등 보일러 플레이트 코드가 누락된 부분이 보이는데 혹시 이유를 알 수 있을까요? 🫠
> 
> 서비스 레포지토리는 아직 서비스가 없기 때문에 따로 생성하지 않았고, 컨트롤러가 필요 없다고 판단된 도메인에는 컨트롤러를 생성하지 않았습니다. 혹시 컨트롤러가 필요한 부분이 있을까요? 제가 만들지 않은 부분은 해당 객체를 생성하는 책임이 다른 부분에 있다고 판단하고 있는데, 알려주시면 감사하겠습니다!

제 생각에도 나중에 필요한 부분이 생길 때 마다 생성하면 될 것 같습니다! 고생하셨습니다 ~ ! 😊

2024-09-29 10:10 UTC, ehs208 approved these changes

2024-09-29 10:11 UTC, dyk-im reviewed
고생하셨습니다. 큰 문제 없는 것 같습니다!

2024-09-29 10:11 UTC, merged