[feat] 예외처리 구축
Leets-Official/Xcellent-BE pull request #6
Opened 2024-10-03 05:06 UTC by dyk-im

## 1. 무슨 이유로 코드를 변경했나요?
예외처리 구축을 위한 기반 코드를 작성했습니다.
<br>

## 2. 어떤 위험이나 장애를 발견했나요?
예외처리 더 세분화할 수 있습니다. (ErrorCode와 GlobalExceptionHandler 코드)
추후 서비스, 컨트롤러 로직에 따른 예외처리가 추가될 수 있습니다.
<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항
기본적인 예외처리 사항 구현하고, 전역으로 처리할 수 있도록 코드 구현했습니다.
<br>

## 5. 추가 사항

2024-10-03 05:53 UTC, yechan-kim requested changes
고생하셨습니다! 코드를 읽어보고 궁금한 점을 적어놨으니 확인 부탁드립니다!
혹시 가능하다면, 예외처리에 대한 테스트 진행 결과를 첨부해 주실 수 있나요?

2024-10-03 05:53 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	}
`GlobalExceptionHandler`에 구현하신 예외가 전부다 있지 않는데, 그렇게 구현하신 이유가 있을까요?
또한, 모든 예외를 `GlobalExceptionHandler`에 추가하는 것을 의도로 작성하신거라면, 그렇게 구현하신 이유가 있을까요?
궁금합니다!!!

2024-10-03 07:14 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	}
찾아보니 global로 처리할 때 따로 처리해도 되고 명시되지 않은 부분은 맨 아래 나머지 예외 처리로 빠지는 걸로 구현했습니다. 그래서 많이 발생할 것 같은 부분은 따로 뺀 것입니다. 일단 수정 염두에 두고있습니다.

2024-10-03 07:15 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	}
테스트는 저녁에 다시 진행한 후 보내드리겠습니다

2024-10-03 07:19 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	}
직접 테스트를 해보지 않아서 모르겠지만 말씀하신 로직으로 진행하게 된다면, HTTP status가 의도한 status로 진행되지 않을 수 있습니다. 테스트를 먼저 진행해 보시고, 결과에 따라서 진행하시면 될 것 같습니다!

2024-10-03 07:44 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	}
넵 알겠습니다 테스트 진행해보고 결과 알려드리겠습니다!

2024-10-03 13:06 UTC, ehs208 submitted a review, later dismissed
고생하셨습니다! 저도 예외처리를 해본적이 없어서인지 이해가 잘 안가는데, 혹시 예외처리하는 로직을 간단하게 설명해주실 수 있을까요?
참고하신 블로그나 자료 첨부해주시면 같이 보겠습니다!

2024-10-03 14:06 UTC, dyk-im commented
일단 예외처리는 에러 코드를 정의한 enum 상수로 ErrorCode가 있고, 에러 발생시 클라이언트에 반환할 ErrorResponse 객체 그리고 각 상황에 맞는 예외인 CustomException들이 정의되어 있습니다. 이는 commonException 이라는 RuntimeException을 상속 받은 객체를 상속 받습니다. 
이러한 예외가 발생하면 각각 컨트롤러나 서비스 로직에서 예외 처리하는 것이 아닌 스프링 어노테이션을 활용해서 중앙에서 전역으로 처리합니다. 그래서 GlobalExceptionHandler를 구현했습니다. 이 핸들러 코드는 세부적인 에러 처리가 필요한 예외를 제외하면 코드의 복잡성을 줄이기 위해 포괄적으로 처리하도록 구현되어 있습니다. 최종적으로 에러 정보를 담은 객체가 전달됩니다.
리츠에 위쓰 프로젝트 코드를 좀 참조했고,
[[https://dmaolon00.tistory.com/entry/Spring-Exception-처리-과정-ErrorCode-CustomException-ControllerAdvice](https://dmaolon00.tistory.com/entry/Spring-Exception-%EC%B2%98%EB%A6%AC-%EA%B3%BC%EC%A0%95-ErrorCode-CustomException-ControllerAdvice)](https://dmaolon00.tistory.com/entry/Spring-Exception-%EC%B2%98%EB%A6%AC-%EA%B3%BC%EC%A0%95-ErrorCode-CustomException-ControllerAdvice)

[[https://velog.io/@letsdev/Spring-예외-처리-쉽게-관심사-나누기-Global-Exception-HandlerController-Advice](https://velog.io/@letsdev/Spring-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EC%89%BD%EA%B2%8C-%EA%B4%80%EC%8B%AC%EC%82%AC-%EB%82%98%EB%88%84%EA%B8%B0-Global-Exception-HandlerController-Advice)](https://velog.io/@letsdev/Spring-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EC%89%BD%EA%B2%8C-%EA%B4%80%EC%8B%AC%EC%82%AC-%EB%82%98%EB%88%84%EA%B8%B0-Global-Exception-HandlerController-Advice)

[[https://velog.io/@tnals1178/Spring-예외처리하기-ExceptionHandler](https://velog.io/@tnals1178/Spring-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0-ExceptionHandler)](https://velog.io/@tnals1178/Spring-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0-ExceptionHandler)
참조자료 입니다!

2024-10-03 21:28 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	}
@SpringBootTest(classes = XcellentBeApplication.class)
class XcellentBeApplicationTests {

        @Autowired
        private GlobalExceptionHandler globalExceptionHandler;

        @Test
        void handleCommonException() {
            FailedSearchException ex = new FailedSearchException("search");
            ResponseEntity<ErrorResponse> response = globalExceptionHandler.handleCommonException(ex);

            ErrorResponse errorResponse = response.getBody();
            assertNotNull(errorResponse);
            System.out.println("HTTP Status: " + errorResponse.getStatus());
            System.out.println("Code: " + errorResponse.getCode());
            System.out.println("Message: " + errorResponse.getMessage());
        }
        @Test
        void handleGenericException() {
            IOException ex1 = new IOException("Generic error");
            ResponseEntity<ErrorResponse> response = globalExceptionHandler.handleGenericException(ex1);
            ErrorResponse errorResponse = response.getBody();
            assertNotNull(errorResponse);

            System.out.println("HTTP Status: " + errorResponse.getStatus());
            System.out.println("Code: " + errorResponse.getCode());
            System.out.println("Message: " + errorResponse.getMessage());
        }
} 
위의 코드를 바탕으로 junit5 테스트를 진행했으며 임의로 에러를 발생하고 포괄적인 예외처리기와 CommonException을 상속 받는 정의된 예외 처리를 진행한 결과 
<img width="551" alt="스크린샷 2024-10-04 오전 6 27 37" src="https://github.com/user-attachments/assets/4a219f23-1619-4be4-a196-3753ae93bfc8">
위와 같이 상태가 전달되고 있음을 확인했습니다. 그리고 코드 추가 수정했습니다.

2024-10-03 22:13 UTC, dyk-im commented
일부 코드 리팩토링, 픽스 그리고 전역 예외 처리 구조 변경과 중복 방지 예외 처리 기능 추가했습니다. 테스트까지 모두 완료했고 리뷰 부탁드리겠습니다.

2024-10-03 22:17 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	}
말씀 주신대로 중복도 있고 코드가 조금 모호한 것 같아 구조를 조금 변경했습니다. 정의한 예외 들은 CommonException을 상속받기 때문에 이 예외 객체를 상속 받는 예외들은 CommonExceptionHandler가 처리하고 status는 해당 객체가 가진 코드가 전달되도록 처리했고 나머지 예외는 GenericExceptionHandler가 처리하도록 하였습니다. 추후 현재 고려되지 않은 예외가 추가된다면 코드를 확장하면 될 것 같습니다.

2024-10-04 05:26 UTC, ehs208 commented
> 일단 예외처리는 에러 코드를 정의한 enum 상수로 ErrorCode가 있고, 에러 발생시 클라이언트에 반환할 ErrorResponse 객체 그리고 각 상황에 맞는 예외인 CustomException들이 정의되어 있습니다. 이는 commonException 이라는 RuntimeException을 상속 받은 객체를 상속 받습니다. 이러한 예외가 발생하면 각각 컨트롤러나 서비스 로직에서 예외 처리하는 것이 아닌 스프링 어노테이션을 활용해서 중앙에서 전역으로 처리합니다. 그래서 GlobalExceptionHandler를 구현했습니다. 이 핸들러 코드는 세부적인 에러 처리가 필요한 예외를 제외하면 코드의 복잡성을 줄이기 위해 포괄적으로 처리하도록 구현되어 있습니다. 최종적으로 에러 정보를 담은 객체가 전달됩니다. 리츠에 위쓰 프로젝트 코드를 좀 참조했고, [[https://dmaolon00.tistory.com/entry/Spring-Exception-처리-과정-ErrorCode-CustomException-ControllerAdvice](https://dmaolon00.tistory.com/entry/Spring-Exception-%EC%B2%98%EB%A6%AC-%EA%B3%BC%EC%A0%95-ErrorCode-CustomException-ControllerAdvice)](https://dmaolon00.tistory.com/entry/Spring-Exception-%EC%B2%98%EB%A6%AC-%EA%B3%BC%EC%A0%95-ErrorCode-CustomException-ControllerAdvice)
> 
> [[https://velog.io/@letsdev/Spring-예외-처리-쉽게-관심사-나누기-Global-Exception-HandlerController-Advice](https://velog.io/@letsdev/Spring-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EC%89%BD%EA%B2%8C-%EA%B4%80%EC%8B%AC%EC%82%AC-%EB%82%98%EB%88%84%EA%B8%B0-Global-Exception-HandlerController-Advice)](https://velog.io/@letsdev/Spring-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EC%89%BD%EA%B2%8C-%EA%B4%80%EC%8B%AC%EC%82%AC-%EB%82%98%EB%88%84%EA%B8%B0-Global-Exception-HandlerController-Advice)
> 
> [[https://velog.io/@tnals1178/Spring-예외처리하기-ExceptionHandler](https://velog.io/@tnals1178/Spring-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0-ExceptionHandler)](https://velog.io/@tnals1178/Spring-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0-ExceptionHandler) 참조자료 입니다!

설명 감사합니다 !!! 😀

2024-10-04 05:33 UTC, yechan-kim requested changes
보내주신 자료 잘 봤습니다! 고생 많으셨습니다!!!
코드를 보고 궁금한 점과 수정이 필요한 부분에 의견을 달아놨으니 읽어보시고 답변 부탁드립니다!!!

2024-10-04 05:33 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	CHAT_ROOM_UNAUTHORIZED(401, "CHAT_ROOM_UNAUTHORIZED","권한이 없는 채팅방입니다."),
권관과 관련된 HTTP 응답 상태 코드는 `401`보다는 `403`이 더 적절해 보입니다!
또한 에러 코드도 `CHAT_ROOM_FORBIDDEN`이 더 적절해 보입니다!

2024-10-04 05:33 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	FAILED_SEARCH(404, "FAILED_SEARCH", "검색할 수 없습니다."),
검색 불가에 대한 예외를 추가한 이유가 있을까요?

2024-10-04 05:33 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/exception/custom/FailedSearchException.java
> +}
코드 컨벤션에 맞지 않는 부분입니다. 수정 부탁드립니다!

2024-10-04 05:33 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/exception/custom/InvalidInputValueException.java
> +}
이 부분도 마찬가지로 수정 부탁드립니다!

2024-10-04 05:33 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/exception/custom/RejectDuplicationException.java
> +}
이 부분도 마찬가지로 수정 부탁드립니다!

2024-10-04 05:35 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	}
확인했습니다! 고생하셨습니다!!!

2024-10-04 05:35 UTC, yechan-kim approved these changes

2024-10-04 05:38 UTC, yechan-kim requested changes
실수로 `Approve`를 눌렀네요 죄송합니다...

2024-10-04 05:49 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	FAILED_SEARCH(404, "FAILED_SEARCH", "검색할 수 없습니다."),
일단 저희가 검색 기능이 있어서 오류, db나 인덱싱 문제, 잘못된 검색 등의 경우가 있을 수도 있다고 판단해서 에러 코드를 하나 만들었습니다. 다른 코드로도 처리는 가능해서 필요없다고 판단되시면 수정하겠습니다!

2024-10-04 05:50 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	CHAT_ROOM_UNAUTHORIZED(401, "CHAT_ROOM_UNAUTHORIZED","권한이 없는 채팅방입니다."),
수정 진행하겠습니다!

2024-10-04 05:52 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	FAILED_SEARCH(404, "FAILED_SEARCH", "검색할 수 없습니다."),
좀 포괄적인 오류 같아서 추후에 자세하게 예외 처리를 하는 것이 좋다고 생각하는데, 어떻게 생각하시나요?

2024-10-04 05:55 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	FAILED_SEARCH(404, "FAILED_SEARCH", "검색할 수 없습니다."),
그러면 일단은 지워두고 추후에 기능보고 에러코드 추가하는 쪽으로 하겠습니다

2024-10-04 05:57 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/exception/custom/FailedSearchException.java
> +}
완료했습니다!

2024-10-04 05:57 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/exception/custom/InvalidInputValueException.java
> +}
완료했습니다!

2024-10-04 05:58 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/exception/custom/RejectDuplicationException.java
> +}
완료했습니다!

2024-10-04 06:11 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/exception/custom/UserNotFoundException.java
> +}
예외 처리 클래스들은 관련된 도메인에서 관리하는 게 좋아 보입니다!
domain/{domain_name}/exception 구조를 통해 관리하는 걸 추천합니다!

2024-10-04 06:39 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/exception/custom/UserNotFoundException.java
> +}
서버 내부 에러, 토큰 관련 에러는 global에 그대로 뒀고 
채팅관련 에러 두 개는 채팅 도메인,
유효하지 못한 값, 게시글 에러는 포스트,
유저 탐색 불가, 중복 방지 에러는 유저로 이동시켰습니다!

2024-10-04 07:04 UTC, yechan-kim requested changes
계속 고생하시네요 ㅠㅠ 코드를 읽다 보니 계속 개선사항이 보여 달게 되네요 ㅠㅠ
마지막으로 검토 부탁드립니다!!!

2024-10-04 07:04 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/post/exception/ArticleNotFoundException.java
> +	}
게시글을 Article과 Post를 같이 사용하는 이유가 있을까요?

2024-10-04 07:04 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	REJECT_DUPLICATION(409,"REJECT_DUPLICATION","중복된 값입니다.");
에러 코드와 에러 메시지를 기준으로 오름차순으로 정렬하는 것이 좋을 것 같습니다!

2024-10-04 07:07 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/post/exception/ArticleNotFoundException.java
> +	}
일단 post는 예약어로 게시물 변수를 post로 사용하면 겹치는 문제가 발생하여 api 명세를 작성하는 과정에서 article로 변경했습니다. 그래서 post가 article이 혼용되고 있습니다. 혹시 수정이 필요하다면 수정하겠습니다!

2024-10-04 07:10 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/post/exception/ArticleNotFoundException.java
> +	}
추후에 `Post`도메인을 `Article`로 단일화 부탁드리겠습니다!
읽어보니까 `Article`로 통일하는 게 좋아 보이네요!

2024-10-04 07:12 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	REJECT_DUPLICATION(409,"REJECT_DUPLICATION","중복된 값입니다.");
수정했습니다!

2024-10-04 07:12 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/domain/post/exception/ArticleNotFoundException.java
> +	}
넵 추후 article로 통일하겠습니다

2024-10-04 07:13 UTC, yechan-kim approved these changes
정말로 고생 많으셨습니다!

2024-10-04 07:15 UTC, merged