[Feat] 로그인 구현
Leets-Official/Xcellent-BE pull request #8
Opened 2024-10-08 14:38 UTC by ehs208

## 1. 무슨 이유로 코드를 변경했나요?

사이트 자체 로그인을 구현 했습니다.

<br>

## 2. 어떤 위험이나 장애를 발견했나요?

블로그를 참고하면서 하다보니 구현은 됐지만, 스프링 시큐리티와 JWT 대한 개념을 완전히 이해하지는 못한 것 같습니다 😅
코드리뷰 해주시면 참고해서 공부해보겠습니다.

<br>

## 3. 관련 스크린샷을 첨부해주세요.

<img width="767" alt="image" src="https://github.com/user-attachments/assets/4cf4787c-511d-40a1-a1c7-2d9513dc8b94">

회원가입 시도시

<img width="779" alt="image" src="https://github.com/user-attachments/assets/cbfa0999-e80b-4532-a631-49c4a7dff176">

같은 이메일 주소로 회원가입 재시도시

<img width="786" alt="image" src="https://github.com/user-attachments/assets/4217aaa8-2f5e-4ffb-8dc0-74f4aa525742">

정상적으로 로그인 시도시

<img width="770" alt="image" src="https://github.com/user-attachments/assets/ea48e4d5-dbef-43bd-a886-0617421e891a">

존재하지 않는 이메일로 로그인 시도시

<br>

## 4. 완료 사항

- 공통 리스폰스 구현
- 스웨거에 로그인 및 회원가입 API 구현
- 로그인/회원가입 상황별 예외처리 구현
- JWT / Spring Security 설정

<br>

## 5. 추가 사항

[참고 블로그](https://ksh-coding.tistory.com/59?category=1065031#%F0%9F%93%95%20%EC%A0%84%EC%B2%B4%20%EB%A1%9C%EA%B7%B8%EC%9D%B8%20%EA%B5%AC%ED%98%84%20%EB%AA%A9%EC%B0%A8-1)

상단의 블로그를 대부분 참고하여 구현했습니다.

2024-10-08 15:02 UTC, yechan-kim requested changes
고생 많으셨습니다! `Customauthenticationfilter`를 통해 로그인을 구현하신 것 같은데, 처음 보는 방식이라 흥미롭게 봤습니다!!!
추가적으로 궁금한 점이나 개선이 필요한 점들에 대해서 의견을 남겨두었으니 확인 부탁드립니다!

2024-10-08 15:02 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/User.java
> +
기존에 정한 프로젝트 구조랑 달라졌는데 혹시 변경하신 이유가 있으실까요?

2024-10-08 15:02 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +@RequestMapping("/api")
해당 엔드 포인트를 `api`로 변경하신 이유가 있으실까요?
`api`라고 하면 엔드 포인트의 범위가 광범해질 것 같습니다!

2024-10-08 15:02 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/dto/UserLoginDto.java
> +}
`DTO`같은 경우에는 request와 response를 나눠서 관리하는 것이 좋다고 생각합니다!
또한 `DTO`같은 경우에는 `class`보다는 `record`로 구현하는게 더 좋다고 생각합니다!

관련된 자료를 첨부해놓을 테니 한번 읽어보세요!
https://velog.io/@oyoungsun/Java-RECORD-DTO%EB%A5%BC-record-type%EC%9C%BC%EB%A1%9C-%EC%84%A4%EC%A0%95%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

2024-10-08 15:02 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/dto/UserSignUpDto.java
> +}
이 부분도 마찬가지 입니다!

2024-10-08 15:02 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/config/SecurityConfig.java
> +		   configuration.setAllowedOrigins(Arrays.asList("http://localhost:3000", "http://localhost:8080", "https://develop.d333radwds380a.amplifyapp.com"));
해당 부분의 들여 쓰기가 이상하네요. 수정 부탁드립니다!

2024-10-08 15:02 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	USER_ALREADY_EXISTS(404 , "ALREADY_EXISTS_EXCEPTION" , "이미 존재하는 사용자입니다." );
이미 존재하는 사용자로 인해 발생하는 예외는 404와 적합하지 않은 것 같습니다.
404는 요청한 내용을 찾지 못했을 때 나오는 오류 코드입니다!
해당 오류는 사전 조건에 실패했을 때 발생하는 412 오류 코드가 더 적합한 것 같습니다!

2024-10-08 15:02 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	// }
해당 로직을 주석처리한 이유가 있을까요?

2024-10-08 19:05 UTC, dyk-im commented
정말 고생 많으셨습니다! 커밋 기록 보면서 로그인, 인증 관련 코드들 봤는데 정말 어렵네요... 자세하게는 모르지만 코드에 이상이나 문제는 크게 없는 것 같습니다!

2024-10-08 19:06 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	// }
저도 이 부분이 궁금했는데 혹시 해당 함수가 문제가 있어서 주석처리 하신 걸까요??

2024-10-08 19:07 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	USER_ALREADY_EXISTS(404 , "ALREADY_EXISTS_EXCEPTION" , "이미 존재하는 사용자입니다." );
혹시 수정하실 일 있으시면 저번에 순서대로 정렬해달라고 리뷰 받아서 정렬도 조심스레 부탁드리겠습니다!

2024-10-09 06:01 UTC, yechan-kim requested changes
코드를 다시 읽어보니 궁금한 점이 더 발견되어 의견을 추가로 남깁니다!

2024-10-09 06:01 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/User.java
> +	private LocalDate userBirthDay;
`userBirthday`는 회원가입을 할 때 입력을 받는 것 같으니 `@NotNull`어노테이션을 붙여주면 더 좋을 것 같습니다!

2024-10-09 06:01 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +	}
`ResponseEntity`의 제네릭 타입이 명시되어 있지 않으면, 가독성 및 안정성이 좋지 않습니다.
코드를 읽어보니 `ResponseEntity<GlobalResponseDto<String>>`으로 명시해 주면 좋을 것 같습니다!

2024-10-09 06:01 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +
`userservice`의 네이밍은 camelCase 스타일로 `userService`로 변경하는 것이 좋다고 생각합니다!

2024-10-09 06:01 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +	}
이 부분은 `GlobalResponseDto`를 사용하지 않았네요. 따로 이유가 있으신가요?
성공 메시지는 `Enum`으로 관리하는 것이 좋다고 생각하는데, 어떻게 생각하시나요?

2024-10-09 06:01 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/service/UserService.java
> +		return "회원가입이 완료되었습니다.";
이 부분도`Enum` 타입의 사용을 고려하는 걸 추천합니다!

2024-10-09 06:01 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/repository/UserRepository.java
> +
이부분도 기존에 정한 프로젝트 구조랑 달라졌는데 혹시 변경하신 이유가 있으실까요?

2024-10-09 06:08 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/response/GlobalResponseDto.java
> +			.message("성공")
`Post` 메서드 같은 경우에는 성공 코드가 `201 Created` 코드를 주로 사용하게 되는데 `200 Ok`만 사용하는 건 적절하지 않다고 생각합니다!

2024-10-09 06:08 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/response/GlobalResponseDto.java
> +	}
Post 메서드 같은 경우에는 성공 코드가 201 Created 코드를 주로 사용하게 되는데 200 Ok만 사용하는 건 적절하지 않다고 생각합니다!

2024-10-09 06:08 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/global/response/GlobalResponseDto.java
> +	}
Post 메서드 같은 경우에는 성공 코드가 201 Created 코드를 주로 사용하게 되는데 200 Ok만 사용하는 건 적절하지 않다고 생각합니다!

2024-10-09 15:23 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/User.java
> +
엇.. 혹시 어떻게 수정해야할지 잘 감이 안오는데 디렉토리 컨벤션을 다시 알려주실 수 있을까요?

2024-10-09 15:25 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +@RequestMapping("/api")
로그인 / 회원가입의 API 경우는 엔드포인트가 /api/user가 아닌 /api/auth로 시작되어, 분리하기 위해 이렇게 설정하게 되었습니다. 😀

2024-10-09 15:29 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/dto/UserLoginDto.java
> +}
아직 `respone`에 필요한 `DTO`는 없어 `UserLoginRequestDto`로 클래스 이름 변경해 두겠습니다!
`record`로 변경은 추후 변경 하겠습니다!

2024-10-09 15:30 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/dto/UserSignUpDto.java
> +}
넵! 추후 반영 하겠습니다!

2024-10-09 15:34 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/global/config/SecurityConfig.java
> +		   configuration.setAllowedOrigins(Arrays.asList("http://localhost:3000", "http://localhost:8080", "https://develop.d333radwds380a.amplifyapp.com"));
이 부분은 IDE 상에선 이상이 없는데 어떻게 수정하면 될까요 😅

2024-10-09 15:35 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/global/error/ErrorCode.java
> +	USER_ALREADY_EXISTS(404 , "ALREADY_EXISTS_EXCEPTION" , "이미 존재하는 사용자입니다." );
수정 했습니다! 정렬도 수정하겠습니다!

2024-10-09 15:38 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/global/error/exception/GlobalExceptionHandler.java
> +	// }
아마 이전에 예외처리 관련 디버깅 하던 도중 주석처리한거 같은데.. 일단 다시 풀어두겠습니다!

2024-10-09 15:39 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/User.java
> +	private LocalDate userBirthDay;
놓쳤던 부분 확인해주셔서 감사합니다! 반영 하겠습니다 😁

2024-10-09 15:42 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +@RequestMapping("/api")
한 컨트롤러에서 사용자를 관리하는 책임과 인증 및 권한 관리 책임을 같이 부여하고 있다고 생각하는데, 컨트롤러를 분리하여 책임을 분리하는 것은 어떻게 생각하시나요?

2024-10-09 15:43 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +	}
반영하겠습니다. 제가 자바 실력이 많이 부족해서 그런데,,, 고치는 이유가 반환 타입을 확실하게 명시해주기 위해서가 맞을까요?

2024-10-09 15:44 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +
놓쳤던 부분 체크해주셔서 감사합니다! ☺️

2024-10-09 15:46 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +	}
이 부분은 Swagger에 API를 띄워주기 위해 설정해둔 부분이라, 실제 서비스 동작에는 영향을 끼치지 않는 부분이라 우선 이렇게 작성해 뒀습니다!

2024-10-09 15:49 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/service/UserService.java
> +		return "회원가입이 완료되었습니다.";
이 메세지의 경우 다른 부분에서는 사용되지 않는 부분인데, 굳이 `Enum`타입을 사용할 필요가 있을까요?!.. `매직 리터럴` 로 처리하는 정도는 괜찮다고 생각됩니다 😇

2024-10-09 15:49 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/repository/UserRepository.java
> +
이 부분도 상단 답변에 남겨두었습니다..!

2024-10-09 16:02 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/global/response/GlobalResponseDto.java
> +	}
우선 오버로딩 사용하여 구현 해놨습니다만,, 좋지 않은 방법이라 추후 수정이 필요할 것 같습니다! 🥲

2024-10-09 16:03 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +	}
관련된 자료를 첨부해 드리겠습니다. 한번 읽어보시는 게 좋을 것 같아요!
https://stir.tistory.com/343

2024-10-09 16:18 UTC, dyk-im commented on src/main/java/com/leets/xcellentbe/global/config/SecurityConfig.java
> +		   configuration.setAllowedOrigins(Arrays.asList("http://localhost:3000", "http://localhost:8080", "https://develop.d333radwds380a.amplifyapp.com"));
저도 전에 그런 오류 발생했었는데, 백스페이스로 지웠다가 다시 줄 바꿔서 해결되기는 했었습니다!

2024-10-09 16:24 UTC, yechan-kim commented on src/main/java/com/leets/xcellentbe/domain/user/User.java
> +
해당 사항은 팀 노션에 기록을 해 두었으니 확인 부탁드립니다!

2024-10-10 08:33 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/global/response/GlobalResponseDto.java
> +	}
이 부분도 위와 마찬가지로 수정 완료했습니다 !

2024-10-10 09:50 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/User.java
> +
반영해서 수정 하였습니다!

2024-10-10 09:54 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/repository/UserRepository.java
> +
변경하였습니다.

2024-10-10 13:49 UTC, ehs208 commented on src/main/java/com/leets/xcellentbe/domain/user/controller/UserController.java
> +@RequestMapping("/api")
분리 완료했습니다!

2024-10-10 13:52 UTC, yechan-kim approved these changes, later dismissed
변경사항 확인했습니다. 고생하셨습니다!

2024-10-10 14:15 UTC, yechan-kim approved these changes

2024-10-10 14:23 UTC, merged